// Code generated by goctl. DO NOT EDIT.
package types

type LoginRep struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	CreateTime int64  `json:"create_time"`
	UpdateTime int64  `json:"UpdateTime"`
}

type Result struct {
	Success string `json:"success"`
	Data    string `json:"data"`
}

type Student struct {
	Name string `json:"name"`
}

type StudentIdParam struct {
	Id int64 `form:"id"`
}
