// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	student "book/service/student/api/internal/handler/student"
	"book/service/student/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TestMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/student/list",
					Handler: student.ListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/student/add",
					Handler: student.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/student/queryById",
					Handler: student.QueryByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/student/edit",
					Handler: student.EditHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/student/delete",
					Handler: student.DeleteHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/student/listPage",
				Handler: listPageHandler(serverCtx),
			},
		},
	)
}
